{
 "title": "Event-Loader",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total events processed",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(events_processed_total)" }
   ]
  },
  {
   "title": "Total blocks processed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(blocks_processed_total)" }
   ]
  },
  {
   "title": "Latest block number",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "block_number{tag='latest'}" }
   ]
  },
  {
   "title": "Current block number",
   "type": "singlestat",
   "description": "Number of a latest block on Node",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(block_number{tag='current',service='blockchain',kubernetes_namespace=\"event-loader-rinkeby\"})"
    }
   ]
  },
  {
   "title": "Current block number",
   "type": "singlestat",
   "description": "Number of a latest block on Node",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(block_number{tag='current',service='blockchain',kubernetes_namespace=\"event-loader-ropsten\"})"
    }
   ]
  },
  {
   "title": "Current block number",
   "type": "singlestat",
   "description": "Number of a latest block on Node",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(block_number{tag='current',service='blockchain',kubernetes_namespace=\"event-loader-mainnet\"})"
    }
   ]
  },
  {
   "title": "Event fetch time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(events_fetch_time_seconds_max) by (kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_namespace}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Messages count by topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none", "label": "Message amount" }
   ],
   "targets": [
    {
     "expr": "sum(message_published_topic_total{kubernetes_namespace=\"event-loader-rinkeby\"}) by (name)",
     "legendFormat": "Rinkeby-{{name}}"
    },
    {
     "expr": "sum(message_published_topic_total{kubernetes_namespace=\"event-loader-ropsten\"}) by (name)",
     "legendFormat": "Ropsten-{{name}}"
    },
    {
     "expr": "sum(message_published_topic_total{kubernetes_namespace=\"event-loader-mainnet\"}) by (name)",
     "legendFormat": "Mainnet-{{name}}"
    }
   ]
  }
 ]
}