eventloader:
  eth:
    node_url: https://rinkeby.infura.io/KoT2OtS1XERWOC0QQAPX
    block_batch_size: 10
  zk:
    url: zookeeper.kafka:2181
  start_block: 3343093

spring:
  kafka:
    bootstrap-servers: bootstrap.kafka:9092
    producer:
      value-serializer: 'org.springframework.kafka.support.serializer.JsonSerializer'
      retries: 5
    consumer:
      value-deserializer: 'org.springframework.kafka.support.serializer.JsonDeserializer'
      group-id: 'ethereum-events-consumer'
    template:
      default-topic: 'ethereum.events.all'
    client-id: 'ethereum-events'