eventloader:
  eth:
    node_url: ${NODE_URL}
    block_batch_size: ${BLOCK_BATCH_SIZE}
  zk:
    url: ${ZOOKEEPER_URL}
  start_block: ${START_BLOCK}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_URL}
    producer:
      value-serializer: 'org.springframework.kafka.support.serializer.JsonSerializer'
      retries: 5
    consumer:
      value-deserializer: 'org.springframework.kafka.support.serializer.JsonDeserializer'
      group-id: ${GROUP_ID}
    template:
      default-topic: ${EVENT_TOPIC}
    client-id: ${CLIENT_ID}